default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: raboy1997
  password: vfrc1997


development:
  <<: *default
  database: dragonarte_development

test:
  <<: *default
  database: dragonarte_test

production:
  <<: *default
  database: dragonarte_production
  username: raboy1997
  password: vfrc1997
